### ISSUE TITLE
Question: When is framing required?

### ISSUE THREAD

**Issue by timmc** [volks73/framed-msgpack#1]
I'm curious about the motivation for this library and its approach to streaming msgpack. From my read of the msgpack spec, you can always find the end of a msgpack document, even if you don't know in advance exactly how large it is. This suggests you could read chunks from a stream until the top level of the document is complete, rather than length-prefixing. Did your use-case have different needs, or was this approach just easier to implement?

**Comment by timmc** [comment]
(I'm now noticing that this library hasn't been touched in 7 years, so I totally understand if you don't even remember the answer!)

**Comment by volks73** [comment]
>This suggests you could read chunks from a stream until the top level of the document is complete, rather than length-prefixing.

Yes, this was my original thought as well. The msgpack spec is essentially a length-prefixed format, so why is any overall "message" length needed?

My original use case was using msgpack as a format for Inter-Process Communication (IPC) and Remote Procedure Call (RPC) between Rust and other programming languages using TCP/IP. The other programmining languages had a very high level TCP/IP stack, where API only allowed reading N bytes at a time. Buffering was done internally as a black box. This meant, to create a streaming parser would be more complicated and possibly inefficient because I would have to always only read 1 byte at a time and lead to double buffering. The other processes and programming language really wanted length-prefixed TCP-based protocols.

I chose length-prefixed msgpack because I wanted an efficient, binary protocol over the wire, as compared to JSON, XML, etc., and added the length-prefix for the entire message to support the high level TCP API in other processes. It looked weird to have a length prefixed in bytes to a JSON/text message.

While it does look weird, I do feel this is still a good structure even if the other processes and programming languages made it easier to implement streaming as the length-prefix is for the network TCP layer, and the msgpack is for the message formatting and decoupled from the transmission/"hardware".

**Comment by timmc** [comment]
Thanks for the reply! And it's funny, in the time since asking you this... I ran smack into the same problem you did, although with a different data structure. Makes sense!
